#######################################################
# 
# MChecker.py
# Python implementation of the Class MChecker
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:10
# Original author: KUBA
# 
#######################################################
from model.MHasher import MHasher

class MChecker:
    m_MHasher= MHasher()

    def verify_data(self, data):
        pass