#######################################################
# 
# MEncryptor.py
# Python implementation of the Class MEncryptor
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:37
# Original author: KUBA
# 
#######################################################
from model.MProfile import MProfile

class MEncryptor:
    m_MProfile= MProfile()

    def decrypt(self, file):
        pass

    def encrypt(self, file):
        pass