#######################################################
# 
# MGenerator.py
# Python implementation of the Class MGenerator
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:12
# Original author: KUBA
# 
#######################################################


class MGenerator:
    def generate(parameters):
        pass