#######################################################
# 
# MLoader.py
# Python implementation of the Class MLoader
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:33
# Original author: KUBA
# 
#######################################################

from model.MProfile import MProfile

class MLoader:
    def load_logins(self):
        pass

    def load_profile(self, name):
        pass