#######################################################
# 
# MProfileMaker.py
# Python implementation of the Class MProfileMaker
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:07
# Original author: KUBA
# 
#######################################################
from model.MHasher import MHasher
from model.MProfile import MProfile

class MProfileMaker(MProfile):
    m_MHasher= MHasher()

    def check_data(string):
        pass

    def __hash_password(string):
        pass

    def __make_profile():
        pass