#######################################################
# 
# MProfile.py
# Python implementation of the Class MProfile
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:29
# Original author: KUBA
# 
#######################################################
from model.MPassword import MPassword
from model.MNote import MNote

class MProfile:
    m_MPassword= MPassword()

    m_MNote= MNote()

    def update(self, update):
        pass

    def update_notes(self, notes):
        pass

    def update_passwords(self, passwords):
        pass