#######################################################
# 
# MEncryptor.py
# Python implementation of the Class MEncryptor
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:37
# Original author: KUBA
# 
#######################################################
from sample.model.MProfile import MProfile
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad

class MEncryptor:

    def decrypt(self, file, key):
        file_in = open(file, 'rb')
        iv = file_in.read(16)
        msg = file_in.read()
        file_in.close()

        cipher = AES.new(key, AES.MODE_CBC, iv=iv)
        og_data = unpad(cipher.decrypt(msg), AES.block_size)
        return og_data

    def encrypt(self, file, key, data):
        msg = data.encode()
        cipher = AES.new(key, AES.MODE_CBC)
        ciphered_data = cipher.encrypt(pad(msg, AES.block_size))
        output_file = open(file, 'wb')
        output_file.write(cipher.iv)
        output_file.write(ciphered_data)
        output_file.close()