#######################################################
# 
# MHasher.py
# Python implementation of the Class MHasher
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:09
# Original author: KUBA
# 
#######################################################
import hashlib


class MHasher:

    def hash(self, string):
        self.hasher = hashlib.sha256()
        self.hasher.update(string.encode())
        return self.hasher.hexdigest()
