#######################################################
# 
# MHasher.py
# Python implementation of the Class MHasher
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:09
# Original author: KUBA
# 
#######################################################


class MHasher:

    def hash(self, string):
        pass