#######################################################
# 
# MNote.py
# Python implementation of the Class MNote
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:31
# Original author: KUBA
# 
#######################################################


class MNote:
    def update(self, update):
        pass