#######################################################
# 
# MNote.py
# Python implementation of the Class MNote
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:31
# Original author: KUBA
# 
#######################################################


class MNote:

    def __init__(self, name, path):
        self._name = name
        self._path = path

    def update(self, update):
        pass

    def get_name(self):
        return self._name