#######################################################
# 
# MPassword.py
# Python implementation of the Class MPassword
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:27
# Original author: KUBA
# 
#######################################################


class MPassword:

    def __init__(self, name, login, password, type, isFavourite):
        self._name = name
        self._login = login
        self._password = password
        self._type = type
        self._isFavourite = isFavourite

    def update(self, update):
        pass
