#######################################################
# 
# MPassword.py
# Python implementation of the Class MPassword
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:27
# Original author: KUBA
# 
#######################################################


class MPassword:

    def __init__(self, name, login, password, type, is_favourite):
        self._name = name
        self._login = login
        self._password = password
        self._type = type
        self._is_favourite = is_favourite

    def update(self, update):
        self._login = update[0]
        self._password = update[1]
        self._is_favourite = update[2]

    def get_name(self):
        return self._name

    def get_is_favourite(self):
        return self._is_favourite

    def get_type(self):
        return self._type

    def get_login(self):
        return self._login

    def get_password(self):
        return self._password
