#######################################################
# 
# MProfile.py
# Python implementation of the Class MProfile
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:29
# Original author: KUBA
# 
#######################################################
from sample.model.MPassword import MPassword
from sample.model.MNote import MNote


class MProfile:

    def __init__(self, name, surname, email, login, passwords={}, notes={}):
        self._name = name
        self._surname = surname
        self._email = email
        self._login = login
        self._passwords = passwords
        self._notes = notes

    def update(self, update):
        pass

    def update_notes(self, notes):
        pass

    def update_passwords(self, passwords):
        pass
