#######################################################
# 
# PAddPasswordWin.py
# Python implementation of the Class PAddPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:41
# Original author: KUBA
# 
#######################################################
from sample.controller.PController import PController
from sample.view.VGenerateWinBefore import VGenerateWinBefore
from sample.model.MPassword import MPassword
from sample.model.MProfile import MProfile


class PAddPasswordWin(PController):

    def __init__(self, main_window, password_list_window, add_win):
        super().__init__(main_window, password_list_window)
        self._generate_win = VGenerateWinBefore(main_window, add_win)

    def generate_button_handle(self):
        self.change_window(self._generate_win)

    def save_button_handle(self, data):
        passwords = self._profile.get_passwords()
        name = data[0]
        login = data[1]
        password = data[2]
        category = data[3]
        url = data[4]
        if name in passwords:
            raise Exception

        password = MPassword(name, login, password, category, False)
        passwords[name.lower()] = password

        self.arrow_button_handle()

    def __update(self, passwords):
        pass

    def set_profile(self, profile):
        self._profile = profile
