#######################################################
# 
# PAddPasswordWin.py
# Python implementation of the Class PAddPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:41
# Original author: KUBA
# 
#######################################################
from sample.controller.PController import PController
from sample.view.VGenerateWinBefore import VGenerateWinBefore
from sample.model.MPassword import MPassword
from sample.model.MProfile import MProfile


class PAddPasswordWin(PController):

    def __init__(self, main_window, password_list_window):
        super().__init__(main_window, password_list_window)

    def generate_button_handle(self):
        pass

    def save_button_handle(self):
        pass

    def __update(self, passwords):
        pass
