#######################################################
# 
# PEncrypWin.py
# Python implementation of the Class PEncrypWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:16:45
# Original author: KUBA
# 
#######################################################
from sample.controller.PMainWin import PMainWin
from sample.model.MEncryptor import MEncryptor
from Crypto.Random import get_random_bytes
import os


class PEncrypWin(PMainWin):

    def __init__(self, main_window):
        super().__init__(main_window)
        self._encryptor = MEncryptor()

    def decrypt_button_handle(self, name):
        encrypteds = self.profile.get_encrypted_list()
        if name in encrypteds:
            return
        file_name = name + '.ope'
        path = 'data/' + self.profile.get_login() + '/encrypted/' + file_name
        msg = self._encryptor.decrypt(path, self.profile.get_password())
        file_path = 'data/' + self.profile.get_login() + '/encrypted/' + name
        file = open(file_path, 'w')
        file.write(msg)
        encrypteds.remove(name)
        os.remove(path)

    def encrypt_button_handle(self, path):
        if path == '':
            return
        try:
            file = open(path, 'r')
            msg = file.read()
        except FileNotFoundError:
            print('Nie znaleziono pliku')
            return
        words = path.split("/")
        file_name = words[len(words) - 1]
        new_path = 'data/' + self.profile.get_login() + '/encrypted/' + file_name + '.ope'
        salt = get_random_bytes(32)
        self._encryptor.encrypt(new_path, msg, salt, self.profile.get_password())
        encrypted_list = self.profile.get_encrypted_list()
        encrypted_list.append(file_name)

    def add_to_list(self, file_list):
        file_list.clear()
        encrypted_list = self.profile.get_encrypted_list()
        for file in encrypted_list:
            file_list.addItem(file)
