#######################################################
# 
# PEncrypWin.py
# Python implementation of the Class PEncrypWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:16:45
# Original author: KUBA
# 
#######################################################
from sample.controller.PMainWin import PMainWin


class PEncrypWin(PMainWin):

    def __init__(self, main_window):
        super().__init__(main_window)

    def decrypt_button_handle(self):
        pass

    def encrypt_button_handle(self):
        pass
