#######################################################
# 
# PPasswordsListWin.py
# Python implementation of the Class PPasswordsListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:37
# Original author: KUBA
# 
#######################################################
'''from view.VPasswordWin import VPasswordWin
from view.VAddPasswordWin import VAddPasswordWin
from view.VAboutAppWin import VAboutAppWin
from view.VNoteListWin import VNoteListWin
from view.VEncrypWin import VEncrypWin
from model.MProfile import MProfile'''
from sample.controller.PMainWin import PMainWin


class PPasswordsListWin(PMainWin):

    def __init__(self, main_window):
        super().__init__(main_window)

    def add_button_handle(self):
        pass

    def choose_button_handle(self):
        pass
