#######################################################
# 
# PPasswordWin.py
# Python implementation of the Class PPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:39
# Original author: KUBA
# 
#######################################################
from sample.model.MPassword import MPassword
from sample.view.VPasswordWin import VPasswordWin

class PPasswordWin:
    m_MPassword= MPassword()

    m_VPasswordWin= VPasswordWin()

    def save_button_handle(self):
        pass

    def show_button_handle(self):
        pass