#######################################################
# 
# PProfileWin.py
# Python implementation of the Class PProfileWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
# from view.VProfileWin import VProfileWin
# from model.MProfile import MProfile
from sample.controller.PController import PController


class PProfileWin(PController):

    def __init__(self, main_window, main_win_after):
        super().__init__(main_window, main_win_after)

    def edit_button_handle(self):
        pass

    def save_button_handle(self, parameters):
        pass

    def show_button_pressed(self):
        pass
