#######################################################
# 
# PProfileWin.py
# Python implementation of the Class PProfileWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
# from view.VProfileWin import VProfileWin
# from model.MProfile import MProfile
from sample.controller.PController import PController


class PProfileWin(PController):

    def __init__(self, main_window, main_win_after):
        super().__init__(main_window, main_win_after)

    def edit_button_handle(self):
        pass

    def save_button_handle(self, parameters):
        self._profile.update(parameters)

    def show_button_pressed(self):
        pass

    def show_data(self, frames):
        name_frame = frames[0]
        surname_frame = frames[1]
        email_frame = frames[2]
        login_frame = frames[3]
        password_frame = frames[4]

        name_frame.setText(self._profile.get_name())
        surname_frame.setText(self._profile.get_surname())
        email_frame.setText(self._profile.get_email())
        login_frame.setText(self._profile.get_login())

    def set_profile(self, profile):
        self._profile = profile
