#######################################################
# 
# PProfileWin.py
# Python implementation of the Class PProfileWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
from Crypto.Random import get_random_bytes

from sample.controller.PController import PController
from sample.model.MEncryptor import MEncryptor


class PProfileWin(PController):

    def __init__(self, main_window, main_win_after):
        super().__init__(main_window, main_win_after)

    def save_button_handle(self, parameters):
        return self._profile.update(parameters)

    def change_password_button_pressed(self, password):
        if password == '':
            return False
        else:
            old_password = self._profile.get_password()
            if self._profile.update_password(password):
                notes = self._profile.get_notes()
                encryptor = MEncryptor()
                login = self._profile.get_login()
                encrypteds = self._profile.get_encrypted_list()

                for file in encrypteds:
                    file = 'data/' + login + '/encrypted/' + file + '.ope'
                    msg = encryptor.decrypt(file,old_password)
                    salt = get_random_bytes(32)
                    encryptor.encrypt(file, msg, salt, password)

                for note in notes:
                    file = notes[note].get_path()
                    msg = encryptor.decrypt(file, old_password)
                    salt = get_random_bytes(32)
                    encryptor.encrypt(file, msg, salt, password)
                return True
            else:
                return False

    def show_data(self, frames):
        name_frame = frames[0]
        surname_frame = frames[1]
        email_frame = frames[2]
        login_frame = frames[3]

        name_frame.setText(self._profile.get_name())
        surname_frame.setText(self._profile.get_surname())
        email_frame.setText(self._profile.get_email())
        login_frame.setText(self._profile.get_login())

    def set_profile(self, profile):
        self._profile = profile
