#######################################################
# 
# PAddPasswordWin.py
# Python implementation of the Class PAddPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:41
# Original author: KUBA
# 
#######################################################
from OnePass.VGenerateWin import VGenerateWin
from OnePass.MPassword import MPassword
from OnePass.MProfile import MProfile

class PAddPasswordWin:
    m_VGenerateWin= VGenerateWin()

    m_MPassword= MPassword()

    m_MProfile= MProfile()

    def generate_button_handle():
        pass

    def save_button_handle():
        pass

    def __update(passwords):
        pass