#######################################################
# 
# PAddPasswordWin.py
# Python implementation of the Class PAddPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:41
# Original author: KUBA
# 
#######################################################
from view.VGenerateWin import VGenerateWin
from model.MPassword import MPassword
from model.MProfile import MProfile

class PAddPasswordWin:
    m_VGenerateWin= VGenerateWin()

    m_MPassword= MPassword()

    m_MProfile= MProfile()

    def generate_button_handle(self):
        pass

    def save_button_handle(self):
        pass

    def __update(self, passwords):
        pass