#######################################################
# 
# PEncrypWin.py
# Python implementation of the Class PEncrypWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:16:45
# Original author: KUBA
# 
#######################################################
from model.MLoader import MLoader
from view.VNoteListWin import VNoteListWin
from view.VGenerateWin import VGenerateWin
from view.VMainWinAfter import VMainWinAfter
from view.VPasswordsListWin import VPasswordsListWin
from model.MEncryptor import MEncryptor
from controller.PMainWin import PMainWin

class PEncrypWin(PMainWin):
    m_VNoteListWin= VNoteListWin()

    m_VGenerateWin= VGenerateWin()

    m_VMainWinAfter= VMainWinAfter()

    m_VPasswordsListWin= VPasswordsListWin()

    m_MEncryptor= MEncryptor()

    m_MLoader= MLoader()

    def decrypt_button_handle(self):
        pass

    def encrypt_button_handle(self):
        pass