#######################################################
# 
# PEncrypWin.py
# Python implementation of the Class PEncrypWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:16:45
# Original author: KUBA
# 
#######################################################
from OnePass.MLoader import MLoader
from OnePass.VNoteListWin import VNoteListWin
from OnePass.VGenerateWin import VGenerateWin
from OnePass.VMainWinAfter import VMainWinAfter
from OnePass.VPasswordsListWin import VPasswordsListWin
from OnePass.MEncryptor import MEncryptor
from OnePass.PMainWin import PMainWin

class PEncrypWin(PMainWin):
    m_VNoteListWin= VNoteListWin()

    m_VGenerateWin= VGenerateWin()

    m_VMainWinAfter= VMainWinAfter()

    m_VPasswordsListWin= VPasswordsListWin()

    m_MEncryptor= MEncryptor()

    m_MLoader= MLoader()

    def decrypt_button_handle():
        pass

    def encrypt_button_handle():
        pass