#######################################################
# 
# PGenerateWin.py
# Python implementation of the Class PGenerateWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:13
# Original author: KUBA
# 
#######################################################
from view.VGenerateWin import VGenerateWin
from model.MGenerator import MGenerator

class PGenerateWin:
    m_VGenerateWin= VGenerateWin()

    m_MGenerator= MGenerator()

    def generate_button_handle(self, parameters):
        pass