#######################################################
# 
# PGenerateWinBefore.py
# Python implementation of the Class PGenerateWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:13
# Original author: KUBA
# 
#######################################################
from controller.PController import PController
from model.MGenerator import MGenerator
from PyQt5 import QtWidgets


class PGenerateWinBefore(PController):

    def __init__(self, generate_win, main_window, main_win_before):
        super().__init__(main_window, main_win_before)
        self._generate_win = generate_win
        self._generator = MGenerator()

    def generate_button_handle(self, parameters):
        pass
