#######################################################
# 
# PGenerateWin.py
# Python implementation of the Class PGenerateWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:13
# Original author: KUBA
# 
#######################################################

from model.MGenerator import MGenerator


class PGenerateWin:

    def __init__(self, generate_win):
        _generate_win = generate_win
        _generator = MGenerator()

    def generate_button_handle(self, parameters):
        pass
