#######################################################
# 
# PGenerateWinBefore.py
# Python implementation of the Class PGenerateWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:13
# Original author: KUBA
# 
#######################################################

from model.MGenerator import MGenerator


class PGenerateWinBefore:

    def __init__(self, generate_win, main_window, main_win_before):
        self.main_window = main_window
        self.main_win_before = main_win_before
        self._generate_win = generate_win
        self._generator = MGenerator()

    def generate_button_handle(self, parameters):
        pass

    def arrow_button_handle(self):
        pass

    def set_main_window(self, main_win):
        self.main_window = main_win
