#######################################################
# 
# PMainWinBefore.py
# Python implementation of the Class PMainWinBefore
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:23
# Original author: KUBA
# 
#######################################################
import sys

from PyQt5 import QtWidgets

from controller.PController import PController
from view.VSignInWin import VSignInWin
from view.VSignUpWin import VSignUpWin
from view.VGenerateWinBefore import VGenerateWinBefore
from view.VAboutAppWin import VAboutAppWin
from model.MLoader import MLoader


class PMainWinBefore(PController):

    def __init__(self, main_win_before, main_window):
        super().__init__(main_window, main_win_before)

        self._loader = MLoader()
        self._about_app_win = VAboutAppWin()
        self._generate_win = VGenerateWinBefore(main_window, self.main_win_before)
        self._sign_up_win = VSignUpWin(main_window, self.main_win_before, self._generate_win)
        self._sign_in_win = VSignInWin(main_window, self._loader, self._sign_up_win, main_win_before, self._generate_win)
        self.main_win_before.show(self.main_window)
        self.main_window.show()

    def about_app_button_handle(self):
        pass

    def generate_button_handle(self):
        self.main_window.close()
        self.main_window = QtWidgets.QMainWindow()
        self._generate_win.update_main_window(self.main_window)
        self._generate_win.show(self.main_window)
        self.main_window.show()

    def __load_logins(self):
        pass

    def sign_in_button_handle(self):
        self.main_window.close()
        self.main_window = QtWidgets.QMainWindow()
        self._sign_in_win.update_main_window(self.main_window)
        self._sign_in_win.show(self.main_window)
        self.main_window.show()

    def sign_up_button_handle(self):
        self.main_window.close()
        self.main_window = QtWidgets.QMainWindow()
        self._sign_up_win.update_main_window(self.main_window)
        self._sign_up_win.show(self.main_window)
        self.main_window.show()
