#######################################################
# 
# PMainWinBefore.py
# Python implementation of the Class PMainWinBefore
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:23
# Original author: KUBA
# 
#######################################################
from view.VSignInWin import VSignInWin
from view.VSignUpWin import VSignUpWin
from view.VGenerateWin import VGenerateWin
from view.VAboutAppWin import VAboutAppWin
from model.MLoader import MLoader

class PMainWinBefore:

    def __init__(self):
        _loader = MLoader()
        _windows_before = [VAboutAppWin(), VGenerateWin(), VSignInWin(), VSignUpWin()]

    def about_app_button_handle(self):
        pass

    def generate_button_handle(self):
        pass

    def __load_logins(self):
        pass

    def sign_in_button_handle(self):
        pass

    def sign_up_button_handle(self):
        pass