#######################################################
# 
# PMainWinAfter.py
# Python implementation of the Class PMainWinAfter
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:42
# Original author: KUBA
# 
#######################################################
from view.VProfileWin import VProfileWin
from view.VNoteListWin import VNoteListWin
from view.VGenerateWin import VGenerateWin
from view.VMainWinBefore import VMainWinBefore
from view.VAboutAppWin import VAboutAppWin
from model.MEncryptor import MEncryptor
from controller.PMainWin import PMainWin

class PMainWinAfter(PMainWin):
    m_VProfileWin= VProfileWin()

    m_VNoteListWin= VNoteListWin()

    m_VGenerateWin= VGenerateWin()

    m_VMainWinBefore= VMainWinBefore()

    m_VAboutAppWin= VAboutAppWin()

    m_MEncryptor= MEncryptor()

    def about_app_button_handle():
        pass

    def encrypt_button_handle():
        pass

    def log_out_button_handle():
        pass

    def profile_button_handle():
        pass