#######################################################
# 
# PMainWinAfter.py
# Python implementation of the Class PMainWinAfter
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:42
# Original author: KUBA
# 
#######################################################
from OnePass.VProfileWin import VProfileWin
from OnePass.VNoteListWin import VNoteListWin
from OnePass.VGenerateWin import VGenerateWin
from OnePass.VMainWinBefore import VMainWinBefore
from OnePass.VAboutAppWin import VAboutAppWin
from OnePass.MEncryptor import MEncryptor
from OnePass.PMainWin import PMainWin

class PMainWinAfter(PMainWin):
    m_VProfileWin= VProfileWin()

    m_VNoteListWin= VNoteListWin()

    m_VGenerateWin= VGenerateWin()

    m_VMainWinBefore= VMainWinBefore()

    m_VAboutAppWin= VAboutAppWin()

    m_MEncryptor= MEncryptor()

    def about_app_button_handle():
        pass

    def encrypt_button_handle():
        pass

    def log_out_button_handle():
        pass

    def profile_button_handle():
        pass