#######################################################
# 
# PMainWin.py
# Python implementation of the Class PMainWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:02:02
# Original author: KUBA
# 
#######################################################
from controller.PController import PController


class PMainWin(PController):

    def __init__(self, main_window):
        super().__init__(main_window)
        self.window_list = None

    def encrypt_file_button_handle(self):
        pass

    def generate_button_handle(self):
        pass

    def home_button_handle(self):
        pass

    def note_button_handle(self):
        pass

    def password_button_handle(self):
        pass

    # [0] -- main_win_after
    # [1] -- password_list_win
    # [2] -- note_list_win
    # [3] -- generate_win
    # [4] -- encryp_win
    def set_window_list(self, win_list):
        self.window_list = win_list
