#######################################################
# 
# PMainWin.py
# Python implementation of the Class PMainWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:02:02
# Original author: KUBA
# 
#######################################################
from OnePass.VEncrypWin import VEncrypWin
from OnePass.VMainWinAfter import VMainWinAfter
from OnePass.VNoteListWin import VNoteListWin
from OnePass.VPasswordsListWin import VPasswordsListWin
from OnePass.VGenerateWin import VGenerateWin

class PMainWin:
    m_VEncrypWin= VEncrypWin()

    m_VMainWinAfter= VMainWinAfter()

    m_VNoteListWin= VNoteListWin()

    m_VPasswordsListWin= VPasswordsListWin()

    m_VGenerateWin= VGenerateWin()

    def encrypt_file_button_handle():
        pass

    def generate_button_handle():
        pass

    def home_button_handle():
        pass

    def note_button_handle():
        pass

    def password_button_handle():
        pass