#######################################################
# 
# PMainWinAfter.py
# Python implementation of the Class PMainWinAfter
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:42
# Original author: KUBA
# 
#######################################################
'''from view.VProfileWin import VProfileWin
from view.VNoteListWin import VNoteListWin
from view.VGenerateWinBefore import VGenerateWinBefore
from view.VMainWinBefore import VMainWinBefore
from view.VAboutAppWin import VAboutAppWin
from model.MEncryptor import MEncryptor'''
from controller.PMainWin import PMainWin
from PyQt5 import QtWidgets


class PMainWinAfter(PMainWin):

    def __init__(self, main_window, main_win_before):
        super().__init__(main_window)
        self.main_win_before = main_win_before

    def about_app_button_handle(self):
        pass

    def encrypt_button_handle(self):
        pass

    def log_out_button_handle(self):
        self.main_window.close()
        self.main_window = QtWidgets.QMainWindow()
        self.main_win_before.update_main_window(self.main_window)
        self.main_win_before.show(self.main_window)
        self.main_window.show()

    def profile_button_handle(self):
        pass