#######################################################
# 
# PNoteWin.py
# Python implementation of the Class PNoteWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:14:38
# Original author: KUBA
# 
#######################################################
'''from view.VGenerateWinBefore import VGenerateWinBefore
from view.VEncrypWin import VEncrypWin
from view.VPasswordsListWin import VPasswordsListWin
from view.VMainWinAfter import VMainWinAfter
from view.VAddNoteWin import VAddNoteWin
from model.MProfile import MProfile'''
from controller.PMainWin import PMainWin


class PNoteWin(PMainWin):

    def __init__(self, main_window):
        super().__init__(main_window)

    def add_button_handle(self):
        pass

    def delete_button_handle(self, note):
        pass

    def edit_button_handle(self):
        pass

    def save_button_handle(self, note):
        pass

    def _update(self, notes):
        pass