#######################################################
# 
# PPasswordsListWin.py
# Python implementation of the Class PPasswordsListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:37
# Original author: KUBA
# 
#######################################################
from view.VPasswordWin import VPasswordWin
from view.VAddPasswordWin import VAddPasswordWin
from view.VAboutAppWin import VAboutAppWin
from view.VNoteListWin import VNoteListWin
from view.VEncrypWin import VEncrypWin
from model.MProfile import MProfile
from controller.PMainWin import PMainWin

class PPasswordsListWin(PMainWin):
    m_VPasswordWin= VPasswordWin()

    m_VAddPasswordWin= VAddPasswordWin()

    m_VAboutAppWin= VAboutAppWin()

    m_VNoteListWin= VNoteListWin()

    m_VEncrypWin= VEncrypWin()

    m_MProfile= MProfile()

    def add_button_handle():
        pass

    def choose_button_handle():
        pass