#######################################################
# 
# PPasswordsListWin.py
# Python implementation of the Class PPasswordsListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:37
# Original author: KUBA
# 
#######################################################
from OnePass.VPasswordWin import VPasswordWin
from OnePass.VAddPasswordWin import VAddPasswordWin
from OnePass.VAboutAppWin import VAboutAppWin
from OnePass.VNoteListWin import VNoteListWin
from OnePass.VEncrypWin import VEncrypWin
from OnePass.MProfile import MProfile
from OnePass.PMainWin import PMainWin

class PPasswordsListWin(PMainWin):
    m_VPasswordWin= VPasswordWin()

    m_VAddPasswordWin= VAddPasswordWin()

    m_VAboutAppWin= VAboutAppWin()

    m_VNoteListWin= VNoteListWin()

    m_VEncrypWin= VEncrypWin()

    m_MProfile= MProfile()

    def add_button_handle():
        pass

    def choose_button_handle():
        pass