#######################################################
# 
# PProfileWin.py
# Python implementation of the Class PProfileWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
from view.VProfileWin import VProfileWin
from model.MProfile import MProfile


class PProfileWin:

    m_MProfile = MProfile()

    def __init__(self, win):
        m_profile_window = win

    def edit_button_handle(self):
        pass

    def save_button_handle(self, parameters):
        pass
