#######################################################
# 
# PProfileWin.py
# Python implementation of the Class PProfileWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
from view.VProfileWin import VProfileWin
from model.MProfile import MProfile

class PProfileWin:
    m_VProfileWin= VProfileWin()

    m_MProfile= MProfile()

    def edit_button_handle():
        pass

    def save_button_handle(parameters):
        pass