#######################################################
# 
# PSignInWin.py
# Python implementation of the Class PSignInWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:17
# Original author: KUBA
# 
#######################################################
from view.VMainWinBefore import VMainWinBefore
from view.VMainWinAfter import VMainWinAfter
from model.MChecker import MChecker
from model.MLoader import MLoader
from model.MEncryptor import MEncryptor
from view.VSignUpWin import VSignUpWin

class PSignInWin:
    m_VMainWinBefore= VMainWinBefore()

    m_VMainWinAfter= VMainWinAfter()

    m_MChecker= MChecker()

    m_MLoader= MLoader()

    m_MEncryptor= MEncryptor()

    m_VSignUpWin= VSignUpWin()

    def forget_button_handle(self):
        pass

    def __load_profile(self, login):
        pass

    def sign_in_button_handle(self):
        pass

    def sign_up_button_handle(self):
        pass

    def __validate_data(self, data):
        pass