#######################################################
# 
# PSignUpWin.py
# Python implementation of the Class PSignUpWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:15
# Original author: KUBA
# 
#######################################################
from view.VSignUpWin import VSignUpWin
from view.VMainWinAfter import VMainWinAfter
from view.VMainWinBefore import VMainWinBefore
from model.MProfileMaker import MProfileMaker

class PSignUpWin:
    m_VSignUpWin= VSignUpWin()

    m_VMainWinAfter= VMainWinAfter()

    m_VMainWinBefore= VMainWinBefore()

    m_MProfileMaker= MProfileMaker()

    def sign_up_button_handle(self):
        pass

    def __validate_data(self):
        pass