#######################################################
# 
# PSignUpWin.py
# Python implementation of the Class PSignUpWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:15
# Original author: KUBA
# 
#######################################################

#from view.VMainWinAfter import VMainWinAfter
from model.MProfileMaker import MProfileMaker


# remember about MainWinAfter

class PSignUpWin:

    def __init__(self, sign_up_win):
        _profile_maker = MProfileMaker()
        _sign_up_win = sign_up_win

    def sign_up_button_handle(self):
        pass

    def __validate_data(self):
        pass
