#######################################################
# 
# VAddNoteWin.py
# Python implementation of the Class VAddNoteWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:14:36
# Original author: KUBA
# 
#######################################################
from sample.controller.PNoteWin import PNoteWin
from sample.view.VMainWin import VMainWin

class VAddNoteWin(VMainWin):
    m_PNoteWin= PNoteWin()

    def delete_button_pressed(self):
        pass

    def save_button_pressed(self):
        pass

    def show(self):
        pass