#######################################################
# 
# VPasswordWin.py
# Python implementation of the Class VPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:33
# Original author: KUBA
# 
#######################################################
from sample.controller.PPasswordWin import PPasswordWin

class VPasswordWin:
    m_PPasswordWin= PPasswordWin()

    def copy_button_pressed(self):
        pass

    def edit_button_pressed(self):
        pass

    def save_button_pressed(self):
        pass

    def show(self):
        pass

    def show_button_pressed(self):
        pass