#######################################################
# 
# VAboutAppWin.py
# Python implementation of the Class VAboutAppWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:04
# Original author: KUBA
# 
#######################################################


class VAboutAppWin:

    def show(self):
        pass
