#######################################################
# 
# VAboutAppWinBefore.py
# Python implementation of the Class VAboutAppWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:04
# Original author: KUBA
# 
#######################################################
from controller.PAboutAppWinBefore import PAboutAppWinBefore
from view.VWindow import VWindow


class VAboutAppWinBefore(VWindow):

    def __init__(self, main_window, main_win_before):
        super().__init__()
        self.controller = PAboutAppWinBefore(main_window, main_win_before)

    def setupUi(self, where):
        pass