#######################################################
# 
# VAddPasswordWin.py
# Python implementation of the Class VAddPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:35
# Original author: KUBA
# 
#######################################################
from OnePass.PAddPasswordWin import PAddPasswordWin

class VAddPasswordWin:
    m_PAddPasswordWin= PAddPasswordWin()

    def generate_button_pressed():
        pass

    def save_button_pressed():
        pass

    def show():
        pass