#######################################################
# 
# VEncrypWin.py
# Python implementation of the Class VEncrypWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:57
# Original author: KUBA
# 
#######################################################
from OnePass.PEncrypWin import PEncrypWin
from OnePass.VMainWin import VMainWin

class VEncrypWin(VMainWin):
    m_PEncrypWin= PEncrypWin()

    def decrypt_button_pressed():
        pass

    def encrypt_button_pressed():
        pass

    def show():
        pass