#######################################################
# 
# VEncrypWin.py
# Python implementation of the Class VEncrypWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:57
# Original author: KUBA
# 
#######################################################
from controller.PEncrypWin import PEncrypWin
from view.VMainWin import VMainWin

class VEncrypWin(VMainWin):

    def __init__(self, main_window):
        super().__init__()
        self.controller = PEncrypWin(main_window)

    def decrypt_button_pressed(self):
        pass

    def encrypt_button_pressed(self):
        pass

    def show(self):
        pass