#######################################################
# 
# VGenerateWin.py
# Python implementation of the Class VGenerateWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:18
# Original author: KUBA
# 
#######################################################

from controller.PGenerateWin import PGenerateWin


class VGenerateWin:

    def __init__(self):
        _controller = PGenerateWin(self)

    def generate_button_pressed(self):
        pass

    def show(self):
        pass
