#######################################################
# 
# VGenerateWin.py
# Python implementation of the Class VGenerateWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:18
# Original author: KUBA
# 
#######################################################
from controller.PMainWinBefore import PMainWinBefore
from controller.PGenerateWin import PGenerateWin

class VGenerateWin:
    m_PMainWinBefore= PMainWinBefore()

    m_PGenerateWin= PGenerateWin()

    def generate_button_pressed(self):
        pass

    def show(self):
        pass