#######################################################
# 
# VMainWinBefore.py
# Python implementation of the Class VMainWinBefore
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:25
# Original author: KUBA
# 
#######################################################
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

from controller.PMainWinBefore import PMainWinBefore


class VMainWinBefore:

    def __init__(self, main_window):
        self.controller = PMainWinBefore(self, main_window)

    def __about_app_button_pressed(self):
        pass

    def __generate_button_pressed(self):
        pass

    def show(self, where):
        self.setupUi(where)

    def _sign_in_button_pressed(self):
        self.controller.sign_in_button_handle()

    def __sign_up_button_pressed(self):
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("QPushButton{\n"
                                 "    backgroung-color:transparent;\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton{\n"
                                         "    background-color:transparent;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setEnabled(True)
        self.bg.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bg.setMinimumSize(QtCore.QSize(800, 600))
        self.bg.setMaximumSize(QtCore.QSize(800, 600))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("img/tło.png"))
        self.bg.setScaledContents(False)
        self.bg.setObjectName("bg")
        self.greeting_label = QtWidgets.QLabel(self.centralwidget)
        self.greeting_label.setGeometry(QtCore.QRect(90, 20, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(22)
        self.greeting_label.setFont(font)
        self.greeting_label.setStyleSheet("color: white")
        self.greeting_label.setObjectName("greeting_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 115, 611, 468))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.generate_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.generate_button.setStyleSheet("background-color:transparent")
        self.generate_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/main_win_before/przycisk_generuj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_button.setIcon(icon)
        self.generate_button.setIconSize(QtCore.QSize(202, 199))
        self.generate_button.setObjectName("generate_button")
        self.gridLayout.addWidget(self.generate_button, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.sign_up_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sign_up_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/main_win_before/przycisk_zarejestruj.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.sign_up_button.setIcon(icon1)
        self.sign_up_button.setIconSize(QtCore.QSize(202, 199))
        self.sign_up_button.setObjectName("sign_up_button")
        self.gridLayout.addWidget(self.sign_up_button, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.about_app_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.about_app_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/main_win_before/przycisk_oapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_app_button.setIcon(icon2)
        self.about_app_button.setIconSize(QtCore.QSize(202, 199))
        self.about_app_button.setObjectName("about_app_button")
        self.gridLayout.addWidget(self.about_app_button, 1, 3, 1, 1)
        self.sign_in_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sign_in_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/main_win_before/przycisk_zaloguj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sign_in_button.setIcon(icon3)
        self.sign_in_button.setIconSize(QtCore.QSize(202, 199))
        self.sign_in_button.setObjectName("sign_in_button")
        self.gridLayout.addWidget(self.sign_in_button, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 9, 61, 581))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.logo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo_male.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 0, 1, 1)
        self.option_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.option_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/przycisk_opcje.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.option_button.setIcon(icon4)
        self.option_button.setIconSize(QtCore.QSize(32, 34))
        self.option_button.setObjectName("option_button")
        self.gridLayout_2.addWidget(self.option_button, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.sign_in_button.clicked.connect(self._sign_in_button_pressed)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.greeting_label.setText(_translate("MainWindow", "WITAJ W ONEPASS"))


if __name__ == '__main__':
    print("Hej")
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    w = VMainWinBefore(main_window)
    sys.exit(app.exec_())
