#######################################################
# 
# VMainWin.py
# Python implementation of the Class VMainWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:02:00
# Original author: KUBA
# 
#######################################################
from view.VWindow import VWindow


class VMainWin(VWindow):

    def __init__(self):
        super().__init__()

    def setupUi(self, where):
        pass

    def encrypt_file_button_pressed(self):
        pass

    def generate_button_pressed(self):
        pass

    def home_button_pressed(self):
        pass

    def note_button_pressed(self):
        pass

    def password_button_pressed(self):
        pass

    def set_window_list(self, win_list):
        self.controller.set_window_list(win_list)
