#######################################################
# 
# VMainWinAfter.py
# Python implementation of the Class VMainWinAfter
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:35
# Original author: KUBA
# 
#######################################################
from controller.PMainWinAfter import PMainWinAfter
from view.VMainWin import VMainWin

class VMainWinAfter(VMainWin):
    m_PMainWinAfter= PMainWinAfter()

    def about_app_button_pressed():
        pass

    def encrypt_button_pressed():
        pass

    def log_out_button_pressed():
        pass

    def profile_button_pressed():
        pass

    def show(profile):
        pass