#######################################################
# 
# VMainWin.py
# Python implementation of the Class VMainWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:02:00
# Original author: KUBA
# 
#######################################################
from OnePass.PMainWin import PMainWin

class VMainWin:
    m_PMainWin= PMainWin()

    def encrypt_file_button_pressed():
        pass

    def generate_button_pressed():
        pass

    def home_button_pressed():
        pass

    def note_button_pressed():
        pass

    def password_button_pressed():
        pass