#######################################################
# 
# VMainWinBefore.py
# Python implementation of the Class VMainWinBefore
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:25
# Original author: KUBA
# 
#######################################################
from controller.PMainWinBefore import PMainWinBefore

class VMainWinBefore:
    m_PMainWinBefore= PMainWinBefore()

    def __about_app_button_pressed(self):
        pass

    def __generate_button_pressed(self):
        pass

    def show(self):
        pass

    def __sign_in_button_pressed(self):
        pass

    def __sign_up_button_pressed(self):
        pass