#######################################################
# 
# VNoteListWin.py
# Python implementation of the Class VNoteListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:55
# Original author: KUBA
# 
#######################################################
from OnePass.VMainWin import VMainWin

class VNoteListWin(VMainWin):
    def add_button_pressed():
        pass

    def edit_button_pressed():
        pass

    def show():
        pass