#######################################################
# 
# VNoteListWin.py
# Python implementation of the Class VNoteListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:55
# Original author: KUBA
# 
#######################################################
from controller.PNoteWin import PNoteWin
from view.VMainWin import VMainWin


class VNoteListWin(VMainWin):

    def __init__(self, main_window):
        super().__init__()
        self.controller = PNoteWin(main_window)

    def add_button_pressed(self):
        pass

    def edit_button_pressed(self):
        pass

    def show(self):
        pass
