#######################################################
# 
# VPasswordsListWin.py
# Python implementation of the Class VPasswordsListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
from controller.PPasswordsListWin import PPasswordsListWin
from view.VMainWin import VMainWin

class VPasswordsListWin(VMainWin):

    def __init__(self, main_window):
        super().__init__()
        self.controller = PPasswordsListWin(main_window)

    def add_button_pressed(self):
        pass

    def choose_button_pressed(self):
        pass

    def show(self):
        pass