#######################################################
# 
# VPasswordWin.py
# Python implementation of the Class VPasswordWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:09:33
# Original author: KUBA
# 
#######################################################
from OnePass.PPasswordWin import PPasswordWin

class VPasswordWin:
    m_PPasswordWin= PPasswordWin()

    def copy_button_pressed():
        pass

    def edit_button_pressed():
        pass

    def save_button_pressed():
        pass

    def show():
        pass

    def show_button_pressed():
        pass