#######################################################
# 
# VPasswordsListWin.py
# Python implementation of the Class VPasswordsListWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
from OnePass.PPasswordsListWin import PPasswordsListWin
from OnePass.VMainWin import VMainWin

class VPasswordsListWin(VMainWin):
    m_PPasswordsListWin= PPasswordsListWin()

    def add_button_pressed():
        pass

    def choose_button_pressed():
        pass

    def show():
        pass