#######################################################
# 
# VProfileWin.py
# Python implementation of the Class VProfileWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 12:01:44
# Original author: KUBA
# 
#######################################################
from controller.PProfileWin import PProfileWin

class VProfileWin:
    m_PProfileWin= PProfileWin()

    def edit_button_pressed(self):
        pass

    def save_button_pressed(self):
        pass

    def show(self,profile):
        pass