#######################################################
# 
# VSignInWin.py
# Python implementation of the Class VSignInWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:21
# Original author: KUBA
# 
#######################################################
from controller.PSignInWin import PSignInWin


class VSignInWin:

    def __init__(self,loader,sign_up_win):
        controller = PSignInWin(loader,sign_up_win)

    def forget_button_pressed(self):
        pass

    def show(self, logins):
        pass

    def sign_in_button_pressed(self):
        pass

    def sign_up_button_pressed(self):
        pass
