#######################################################
# 
# VSignInWin.py
# Python implementation of the Class VSignInWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:21
# Original author: KUBA
# 
#######################################################
from controller.PSignInWin import PSignInWin

class VSignInWin:
    m_PSignInWin= PSignInWin()

    def forget_button_pressed():
        pass

    def show(logins):
        pass

    def sign_in_button_pressed():
        pass

    def sign_up_button_pressed():
        pass