#######################################################
# 
# VSignInWin.py
# Python implementation of the Class VSignInWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:21
# Original author: KUBA
# 
#######################################################
from PyQt5 import QtWidgets, QtCore, QtGui

from controller.PSignInWin import PSignInWin


class VSignInWin:

    def __init__(self, main_window, loader, sign_up_win, main_win_before):
        self.controller = PSignInWin(main_window, loader, sign_up_win, main_win_before)

    def forget_button_pressed(self):
        pass

    def show(self, where, logins=''):
        self.setupUi(where)

    def sign_in_button_pressed(self):
        pass

    def sign_up_button_press(self):
        pass

    def arrow_button_press(self):
        self.controller.arrow_button_handle()

    def update_main_window(self, main_win):
        self.controller.set_main_window(main_win)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 600)
        MainWindow.setStyleSheet("QLabel{\n"
                                 "    font: 12pt \"Rubik\";\n"
                                 "    color:white;\n"
                                 "}\n"
                                 "QLineEdit{\n"
                                 "    font: 12pt \"Rubik\";\n"
                                 "    color:white;\n"
                                 "    background: rgb(119,119,119);\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton{\n"
                                 "    font: 8pt \"Rubik\";\n"
                                 "    color:white;\n"
                                 "    background: transparent;\n"
                                 "    border-radius:10px\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 360, 600))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("img/tło_logowanie.png"))
        self.bg.setObjectName("bg")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 240, 341, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 3, 0, 1, 1)
        self.forget_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.forget_button.setObjectName("forget_button")
        self.gridLayout.addWidget(self.forget_button, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        self.password_frame = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_frame.setObjectName("password_frame")
        self.gridLayout.addWidget(self.password_frame, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        self.login_frame = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.login_frame.setObjectName("login_frame")
        self.gridLayout.addWidget(self.login_frame, 1, 1, 1, 1)
        self.sign_up_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sign_up_button.setObjectName("sign_up_button")
        self.gridLayout.addWidget(self.sign_up_button, 5, 1, 1, 1)
        self.login_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.sign_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_button.setGeometry(QtCore.QRect(160, 440, 161, 31))
        self.sign_in_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/sign_in/przycisk_zaloguj.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.sign_in_button.setIcon(icon)
        self.sign_in_button.setIconSize(QtCore.QSize(161, 34))
        self.sign_in_button.setObjectName("sign_in_button")
        self.arrow_button = QtWidgets.QPushButton(self.centralwidget)
        self.arrow_button.setGeometry(QtCore.QRect(15, 15, 41, 41))
        self.arrow_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/przycisk_strzałka.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_button.setIcon(icon1)
        self.arrow_button.setIconSize(QtCore.QSize(34, 31))
        self.arrow_button.setObjectName("arrow_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.arrow_button.clicked.connect(self.arrow_button_press)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOGOWANIE"))
        self.password_label.setText(_translate("MainWindow", "HASŁO"))
        self.forget_button.setText(_translate("MainWindow", "Nie pamiętasz hasła?"))
        self.sign_up_button.setText(_translate("MainWindow", "Załóż konto!"))
        self.login_label.setText(_translate("MainWindow", "LOGIN"))
