#######################################################
# 
# VSignUpWin.py
# Python implementation of the Class VSignUpWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:20
# Original author: KUBA
# 
#######################################################
from controller.PSignUpWin import PSignUpWin



class VSignUpWin:

    def __init__(self):
        controller = PSignUpWin(self)

    def show(self):
        pass

    def sign_up_button_pressed(self):
        pass
