#######################################################
# 
# VSignUpWin.py
# Python implementation of the Class VSignUpWin
# Generated by Enterprise Architect
# Created on:      04-kwi-2020 11:43:20
# Original author: KUBA
# 
#######################################################
from controller.PSignUpWin import PSignUpWin

class VSignUpWin:
    m_PSignUpWin= PSignUpWin()

    def show():
        pass

    def sign_up_button_pressed():
        pass